# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

cache:
  directories:
  - $HOME/.ccache

env:
  matrix:
    - CONFIG=travis_

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "YT6cqW3KpaeZmhtaVQkWVpX1i4Gw5QbwlevR9xy7mwG5+yGZ67tk4LuhxkmxCoC9sN7624gKctJhRzgPoqz9GdAQm2GouaXILNakSxjf5GwnRb74IL5Tw3POs+MJsugoMVnlIA01d9vsK7nkCx86uGxONCSRla3KRKIRdzP31du4RFiLoYEurNsmgp4muKGUUxnlwoveRFxwOnF6FvokMVGNU5cFzSYKE/pgzIGgfVEaTXbLJijM0klvcZzr0j9BLwscn1pUrAyKixFOMr/nTeYFqtYxH+iq2IyzRk+cZeyG7Y0T0MSq0c3Jmw5AQ5p3Z2OhaY2mRO+MTjQlac+sdU5VFBvIekVx3iOG50NoVstUNQw7LQfFx6tX0gbI0oXKQmZ9FNknv/oQ1KV3dhBLDb1Txo8K1PtYKN7JcPF8YDOMHnb5xtJdNLf3El9cboLElOK9uGwI6PUflN85uBqzCsUpILycxYfNe9XWZABR2FtUZZ94nHtI9Udhqbougfh1aFIgyGGeNX8XcpEo2gEvEWrrOD3BTc2KLecwZAT/OUsagFQVPQ1+4d851eV8LhtoPwFrwaTPPj7omHBcKV0xOX7addLD7OzWgLPoiD51RkxPmhtT58nZrlqW0vLF5dzPEnHKn8lb3xtGTqsQCT7dvVeeJX8mr9jQkFxcAgztAro="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-ci-setup=1
      source run_conda_forge_build_setup

script:
  # ccache uses the compiler command line to generate the cache keys, so we can't have a
  # different path for every build. ccache provides CCACHE_BASEDIR variable to solve this
  # but it's better to avoid setting it as it has some side effects.
  - conda build --no-build-id ./recipe -m ./.ci_support/${CONFIG}.yaml

  - upload_or_check_non_existence ./recipe conda-forge --channel=main -m ./.ci_support/${CONFIG}.yaml
